### ISSUE TITLE
com.caoccao.javet.exceptions.JavetException: Javet library is not loaded because <null>

### ISSUE THREAD

**Issue by braddi** [caoccao/Javet#179]
I'm was using **Javet** without any problem locally on my machine, but when I deployed it on **AWS Elastic Beans** it didn't work.

I guess that Javet is not supported on Fedora ?

I really like the performance of Javet over J2V8 and studying the possibility if migration to it .

**This the aws enviroment details :** 
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"

### This is the exception that happened : 
**com.caoccao.javet.exceptions.JavetException: Javet library is not loaded because <null>**
        at com.caoccao.javet.interop.JavetClassLoader.load(JavetClassLoader.java:93) ~[javet-1.1.6.jar:?]
        at com.caoccao.javet.interop.V8Host.loadLibrary(V8Host.java:430) ~[javet-1.1.6.jar:?]
        at com.caoccao.javet.interop.V8Host.<init>(V8Host.java:68) ~[javet-1.1.6.jar:?]
        at com.caoccao.javet.interop.V8Host.<init>(V8Host.java:42) ~[javet-1.1.6.jar:?]
        at com.caoccao.javet.interop.V8Host$V8InstanceHolder.<clinit>(V8Host.java:491) ~[javet-1.1.6.jar:?]
        at com.caoccao.javet.interop.V8Host.getV8Instance(V8Host.java:120) ~[javet-1.1.6.jar:?]
        ....
        Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at com.caoccao.javet.interop.JavetClassLoader.load(JavetClassLoader.java:88) ~[javet-1.1.6.jar:?]
        ... 26 more
**Caused by: com.caoccao.javet.exceptions.JavetException: Failed to read /var/cache/tomcat8/temp/javet/29221/libjavet-v8-linux-x86_64.v.1.1.6.so**
"inbound-consumer-thread.log" [readonly] 283260L, 59061061B                                                         

        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4763) [catalina.jar:8.5.75]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5232) [catalina.jar:8.5.75]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183) [catalina.jar:8.5.75]
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:753) [catalina.jar:8.5.75]
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:727) [catalina.jar:8.5.75]
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:695) [catalina.jar:8.5.75]
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:1016) [catalina.jar:8.5.75]
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1903) [catalina.jar:8.5.75]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_312]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_312]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
**Caused by: java.lang.reflect.InvocationTargetException**
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at com.caoccao.javet.interop.JavetClassLoader.load(JavetClassLoader.java:88) ~[javet-1.1.6.jar:?]
        ... 26 more
**Caused by: com.caoccao.javet.exceptions.JavetException: Failed to read /var/cache/tomcat8/temp/javet/29221/libjavet-v8-linux-x86_64.v.1.1.6.so**
        at com.caoccao.javet.interop.loader.JavetLibLoader.load(JavetLibLoader.java:375) ~[javet-1.1.6.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at com.caoccao.javet.interop.JavetClassLoader.load(JavetClassLoader.java:88) ~[javet-1.1.6.jar:?]
        ... 26 more
**Caused by: java.lang.UnsatisfiedLinkError: /var/cache/tomcat8/temp/javet/29221/libjavet-v8-linux-x86_64.v.1.1.6.so: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /var/cache/tomcat8/temp/javet/29221/libjavet-v8-linux-x86_64.v.1.1.6.so)**
        at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934) ~[?:1.8.0_312]
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817) ~[?:1.8.0_312]
        at java.lang.Runtime.load0(Runtime.java:810) ~[?:1.8.0_312]
        at java.lang.System.load(System.java:1088) ~[?:1.8.0_312]
        at com.caoccao.javet.interop.loader.JavetLibLoader.load(JavetLibLoader.java:360) ~[javet-1.1.6.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_312]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_312]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_312]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_312]
        at com.caoccao.javet.interop.JavetClassLoader.load(JavetClassLoader.java:88) ~[javet-1.1.6.jar:?]
        ... 26 more

**Comment by caoccao** [comment]
Please make sure you have `GLIBC_2.29` installed. #26 may give you some ideas though it is about `GLIBCXX_3.4.26`.

**Comment by braddi** [comment]
I will try that, Thank you for your reply !!!
