### ISSUE TITLE
Callback signature mismatches

### ISSUE THREAD

**Issue by IkeVoodoo** [caoccao/Javet#231]
# Stack Trace
```java
Caused by: com.caoccao.javet.exceptions.JavetException: Callback signature mismatches: expected parameter type is interface java.lang.Runnable, actual parameter type is class com.caoccao.javet.entities.JavetEntityFunction
	at com.caoccao.javet.interop.callback.V8FunctionCallback.convert(V8FunctionCallback.java:299)
	at com.caoccao.javet.interop.callback.V8FunctionCallback.receiveCallback(V8FunctionCallback.java:386)
	... 6 more
```
*Edited exception: I pasted an old exception where I was playing around with params, my bad wops

# Environment
**Javet Version**: 2.0.4
**Java Version**:
```
java 19.0.1 2022-10-18
Java(TM) SE Runtime Environment (build 19.0.1+10-21)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)
```
**OS**: Windows 11

# JavaScript Code
```js
test(() => {
    console.log("Hello, World!");
})
```

# Java Code (Setup)
```java
runtime.getGlobalObject().bindFunction("test", new JavetCallbackContext(Test.class, Test.class.getDeclaredMethod("test", Runnable.class)));
runtime.setConverter(new JavetBridgeConverter());

runtime.getExecutor(file).executeVoid(); // Loading from file
```

# Java Code (test method)
```java
public static void test(Runnable runnable) {
    runnable.run();
}
```

**Comment by caoccao** [comment]
Your sample code doesn't actually activate the `JavetBridgeConverter` because it injects object `test` via raw Javet API instead of the converter.

I suggest you to inject an instance of `Test` directly. E.g.

```java
runtime.setConverter(new JavetBridgeConverter());
runtime.getGlobalObject().set("test", new Test());
```

**Comment by IkeVoodoo** [comment]
Oh, well I am injecting directly because I need to use `test` rather than `test.test`, is there a way to do that?

**Comment by IkeVoodoo** [comment]
Ignore my other reply, it works, thanks!
