### ISSUE TITLE
The 'Node sqlite3' module causes JVM crash

### ISSUE THREAD

**Issue by rongrong1000** [caoccao/Javet#343]
``` java
public static void main(String[] args) {
        try (NodeRuntime nodeRuntime = V8Host.getNodeInstance().createV8Runtime()) {
            nodeRuntime.getExecutor("""
                    const sqlite3 = require("sqlite3")
                                        
                    sqlite = new sqlite3.Database("./sqlite.db", (err) => {
                        if (err) {
                            console.error('Error opening database: ', err.message);
                        } else {
                            console.log('Connected to the SQLite database.');
                        }
                    })
                    """).execute();
        } catch (Exception e) {

        }
    }
``` 

``` 
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000000000000, pid=21208, tid=21304
#
# JRE version: Java(TM) SE Runtime Environment (21.0.1+12) (build 21.0.1+12-LTS-29)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (21.0.1+12-LTS-29, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [node_sqlite3.node+0x167be]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
```

`npm i sqlite3`

javet is 3.1.2

**Comment by caoccao** [comment]
Please review this [doc](https://www.caoccao.com/Javet/reference/resource_management/modularization.html#deal-with-native-modules).

**Comment by rongrong1000** [comment]
> Please review this [doc](https://www.caoccao.com/Javet/reference/resource_management/modularization.html#deal-with-native-modules).

use `Manual Patch Native Modules on Windows` 
```
com.caoccao.javet.exceptions.JavetExecutionException: Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\workspace\java\projects\sss\node_modules\sqlite3\build\Release\node_sqlite3.node
	at com.caoccao.javet.interop.V8Native.scriptExecute(Native Method)
	at com.caoccao.javet.interop.V8Runtime.execute(V8Runtime.java:1047)
	at com.caoccao.javet.interop.executors.V8StringExecutor.execute(V8StringExecutor.java:107)
	at com.caoccao.javet.interop.IV8Executable.execute(IV8Executable.java:44)
	at org.example.func.Why.main(Why.java:37)
```
`Change the DLL name from node.exe to libjavet-node-windows-x86_64.v.x.x.x.dll where x.x.x needs to be replaced with the actual Javet version.`

Is this path issue caused by 'javet'

**Comment by rongrong1000** [comment]
> Please review this [doc](https://www.caoccao.com/Javet/reference/resource_management/modularization.html#deal-with-native-modules).

```
com.caoccao.javet.exceptions.JavetExecutionException: Error: A dynamic link library (DLL) initialization routine failed.
\\?\D:\workspace\java\projects\sss\node_modules\sqlite3\build\Release\node_sqlite3.node
	at com.caoccao.javet.interop.V8Native.scriptExecute(Native Method)
	at com.caoccao.javet.interop.V8Runtime.execute(V8Runtime.java:1047)
	at com.caoccao.javet.interop.executors.V8StringExecutor.execute(V8StringExecutor.java:107)
	at com.caoccao.javet.interop.IV8Executable.execute(IV8Executable.java:44)
	at org.example.func.Why.main(Why.java:37)
```
use `Manual Patch Native Modules on Windows`

now, `DIRECTORY_ENTRY_DELAY_IMPORT` Dll Name is `libjavet-node-windows-x86_64.v.3.1.2.dll` 

Seems to have triggered an error regarding the path

**Comment by caoccao** [comment]
The patch on Windows requires the deep understanding on how it work. I suggest you try `patchelf` on Linux.

**Comment by rongrong1000** [comment]
Understood, this doesn't seem too simple. I plan to use 'JDBC' to package it as a 'js object' to manipulate sqlite

**Comment by caoccao** [comment]
That looks good.
