### ISSUE TITLE
Can Javet easily run Node.js as a subprocess?

### ISSUE THREAD

**Issue by lihaoyi** [caoccao/Javet#405]
I'm hitting issues with using Javet in-process in a dynamic classloader environment, because loading the native binary into the JVM doesn't work well when done in multiple classloaders. Due to the nature of the system it's hard to hoist Javet up to the stable parent classloader

```
[2] Oct 09, 2024 10:55:57 AM com.caoccao.javet.utils.JavetDefaultLogger error
[2] SEVERE: Native Library /private/var/folders/rt/f1pd6fz92x3__6jg0cmgdd580000gn/T/javet/27157/libjavet-v8-macos-arm64.v.3.1.6.dylib already loaded in another classloader
[2] Oct 09, 2024 10:55:57 AM com.caoccao.javet.utils.JavetDefaultLogger error
[2] SEVERE: java.lang.UnsatisfiedLinkError: Native Library /private/var/folders/rt/f1pd6fz92x3__6jg0cmgdd580000gn/T/javet/27157/libjavet-v8-macos-arm64.v.3.1.6.dylib already loaded in another classloader
[2] 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:201)
[2] 	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
[2] 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
[2] 	at java.base/java.lang.Runtime.load0(Runtime.java:755)
[2] 	at java.base/java.lang.System.load(System.java:1953)
[2] 	at com.caoccao.javet.interop.loader.JavetLibLoader.load(JavetLibLoader.java:357)
```

Currently I'm spawning a new JVM subprocess containing Javet which then runs Node internally. This works, but it seems to me the entire wrapper-JVM-subprocess is redundant.

Ideally I'd just be able to spin up a separate Node.js subprocess to run my Javascript stuff. I understand Javet already basically bundles the entire Node dll/dylib, would it be possible to use Javet to spawn node in a subprocess rather than loading it in-process?

**Comment by caoccao** [comment]
Please check this [doc](https://www.caoccao.com/Javet/reference/resource_management/load_and_unload.html) out. You may follow the steps:

1. Save the Javet native binaries to somewhere.
2. Implement `IJavetLibLoadingListener` or specify some env vars to have Javet load the native binaries stored in step 1.

You may also refer to #100 which is about how Javet works in OSGi.

**Comment by lihaoyi** [comment]
Thanks! will take a look
