### ISSUE TITLE
libjavet-v8-macos-arm64.v.4.0.0.dylib is not found

### ISSUE THREAD

**Issue by jdbranham** [caoccao/Javet#412]
After upgrading to v4.0.0 I see this error.  
It might be something specific to my environment because I downgraded to the latest 3.x and see the same issue.  

Note - it works fine on v3.1.3

```
Caused by: com.caoccao.javet.exceptions.JavetException: Javet library /libjavet-v8-macos-arm64.v.4.0.0.dylib is not found
	at com.caoccao.javet.interop.loader.JavetLibLoader.getResourceFileName(JavetLibLoader.java:303)
	at com.caoccao.javet.interop.loader.JavetLibLoader.load(JavetLibLoader.java:335)
```

**Comment by caoccao** [comment]
Please leave your maven or gradle setup, or a repo that could reproduce the issue. So far, no one else has ever reported such issue.

**Comment by jdbranham** [comment]
Turns out the disk was low on space - whoops!

4.0.0 is working great on Arm64

🙏 🎉 🙂
