### ISSUE TITLE
setRequireRootDirectory and setWorkingDirectory not working

### ISSUE THREAD

**Issue by hajekj14** [caoccao/Javet#56]
Try to set working dir and root directory for resolve node_modules but it was fail

Java:
```
        File nodeScript = new File("C:\\Users\\hajek\\scripts\\test\\main.js");
        this.nodeRuntime = V8Host.getNodeInstance().createV8Runtime();
        this.nodeRuntime.getNodeModule(NodeModuleModule.class).setRequireRootDirectory(new File(nodeScript.getParent()).toPath());
        this.nodeRuntime.getNodeModule(NodeModuleProcess.class).setWorkingDirectory(new File(nodeScript.getParent()).toPath());
        this.nodeRuntime.getExecutor(nodeScript).execute();
```

main.js (node_modules are installed in C:\Users\hajek\scripts\test\):
```
var cpus = require('cpus');
console.log(cpus().length);
```

exception:
```
Exception in thread "main" com.caoccao.javet.exceptions.JavetExecutionException: Error: Cannot find module 'cpus'
Require stack:
-  C:\Users\hajek\scripts\test
        at com.caoccao.javet.interop.V8Native.execute(Native Method)
        at com.caoccao.javet.interop.V8Runtime.execute(V8Runtime.java:338)
        at com.caoccao.javet.interop.executors.V8StringExecutor.execute(V8StringExecutor.java:54)
        at com.caoccao.javet.interop.IV8Executable.execute(IV8Executable.java:41)
        at com.hajekj14.platform.win.WinNodeEngine.exec(WinNodeEngine.java:33)
        at com.hajekj14.platform.win.Platform.main(Platform.java:15)

```

**Comment by caoccao** [comment]
Do you mean `os.cpus()`? https://nodejs.org/docs/latest-v14.x/api/os.html#os_os_cpus

``` js
const os = require('os');
console.log(os.cpus());
```

That will give you.

``` json
[
  {
    model: 'Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz',
    speed: 2808,
    times: { user: 465484, nice: 0, sys: 574953, idle: 4845578, irq: 63765 }
  },
  {
    model: 'Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz',
    speed: 2808,
    times: { user: 435796, nice: 0, sys: 388562, idle: 5061296, irq: 14046 }
  },
  ...
]

**Comment by hajekj14** [comment]
Sorry, I did not write it clear. It is about require("cpus"), cpus(just for debbuging) is module inside "node_module" and problem is with loading, Javet raise exception with module "cpus" not found. So I guess problem was with setRequireRootDirectory or  setWorkingDirectory maybe I just set it wrongly.

THX.

**Comment by hajekj14** [comment]
I am expecting when I set setRequireRootDirectory a setWorkingDirectory to parent directory of target script then NodeRuntime automatically find required modules from node_module.

**Comment by caoccao** [comment]
I don't think that's a built-in module in v14.16.x which is the one Javet relies on. Here is what I got in REPL.

```
Welcome to Node.js v14.16.1.
Type ".help" for more information.
> const cpus = require('cpus');
Uncaught Error: Cannot find module 'cpus'
Require stack:
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '<repl>' ]
}
```

**Comment by caoccao** [comment]
As the [doc](https://github.com/caoccao/Javet/blob/main/docs/reference/modularization.rst) suggested, it's better to place the entry script in a dedicated folder staying with node_modules side by side. E.g.

```
root
├─node_modules
│  └─module1
│      └─module1.js
└─test
    └─main.js
```

You don't need to call `setRequireRootDirectory()` and `setWorkingDirectory()`, because `getExecutor()` does that internally. Any attempt before `getExecutor()` will be overridden by `getExecutor()`.
