### ISSUE TITLE
trying to use javet in a minecraft server plugin, running into issues

### ISSUE THREAD

**Issue by hb432** [caoccao/Javet#58]
In my `pom.xml` i have the following:

```xml
<dependency>
   <scope>provided</scope>
   <groupId>org.spigotmc</groupId>
   <artifactId>spigot-api</artifactId>
   <version>1.8-R0.1-SNAPSHOT</version>
</dependency>
```

And in my `Main.java` i have the following:

```
@Override
public void onLoad() {
   try {
      V8Runtime v8Runtime = V8Host.getNodeInstance().createV8Runtime();
      System.out.println(v8Runtime.getExecutor("'test'").executeString());
   } catch (Exception error) {
      // discard errors
   }
}
```

However, when I start the plugin, I get the following error:

```
[15:42:54 INFO]: [grakkit] Loading grakkit v4.1.4
[15:42:54 ERROR]: [com.caoccao.javet.interop.JavetLibLoader] Failed to clean up /tmp/javet.
[15:42:55 ERROR]: [com.caoccao.javet.interop.JavetLibLoader] java.lang.NullPointerException: Cannot read the array length because "<local1>" is null
	at com.caoccao.javet.interop.JavetLibLoader.purgeLegacyLibraries(JavetLibLoader.java:66)
	at com.caoccao.javet.interop.JavetLibLoader.<clinit>(JavetLibLoader.java:51)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.caoccao.javet.interop.JavetClassLoader.load(JavetClassLoader.java:62)
	at com.caoccao.javet.interop.V8Host.loadLibrary(V8Host.java:415)
	at com.caoccao.javet.interop.V8Host.<init>(V8Host.java:76)
	at com.caoccao.javet.interop.V8Host.<init>(V8Host.java:40)
	at com.caoccao.javet.interop.V8Host$NodeInstanceHolder.<clinit>(V8Host.java:480)
	at com.caoccao.javet.interop.V8Host.getNodeInstance(V8Host.java:116)
	at grakkit.Main.onLoad(Main.java:15)
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:399)
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.reload(CraftServer.java:955)
	at org.bukkit.Bukkit.reload(Bukkit.java:769)
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821)
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:784)
	at net.minecraft.server.dedicated.DedicatedServer.handleCommandQueue(DedicatedServer.java:518)
	at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:480)
	at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1406)
	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1188)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
	at java.base/java.lang.Thread.run(Thread.java:831)

[15:42:55 ERROR]: [org.bukkit.craftbukkit.v1_17_R1.CraftServer] 'long com.caoccao.javet.interop.V8Native.createV8Runtime(java.lang.String)' initializing grakkit v4.1.4 (Is it up to date?)
java.lang.UnsatisfiedLinkError: 'long com.caoccao.javet.interop.V8Native.createV8Runtime(java.lang.String)'
	at com.caoccao.javet.interop.V8Native.createV8Runtime(Native Method) ~[?:?]
	at com.caoccao.javet.interop.V8Host.createV8Runtime(V8Host.java:264) ~[?:?]
	at com.caoccao.javet.interop.V8Host.createV8Runtime(V8Host.java:241) ~[?:?]
	at com.caoccao.javet.interop.V8Host.createV8Runtime(V8Host.java:228) ~[?:?]
	at grakkit.Main.onLoad(Main.java:15) ~[?:?]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.loadPlugins(CraftServer.java:399) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.reload(CraftServer.java:955) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.Bukkit.reload(Bukkit.java:769) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchCommand(CraftServer.java:821) ~[patched_1.17.1.jar:git-Paper-90]
	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.dispatchServerCommand(CraftServer.java:784) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:518) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:480) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1406) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1188) ~[patched_1.17.1.jar:git-Paper-90]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[patched_1.17.1.jar:git-Paper-90]
	at java.lang.Thread.run(Thread.java:831) [?:?]
```

Note that Javet is being shaded via the maven shade plugin:

```xml
<plugin>
   <groupId>org.apache.maven.plugins</groupId>
   <artifactId>maven-shade-plugin</artifactId>
   <version>3.2.4</version>
   <executions>
      <execution>
         <phase>package</phase>
         <goals>
            <goal>shade</goal>
         </goals>
         <configuration>
            <createDependencyReducedPom>false</createDependencyReducedPom>
            <transformers>
               <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
            </transformers>
         </configuration>
      </execution>
   </executions>
</plugin>
```

Also note that bukkit/spigot/paper servers (the platform I am using this on) do not immediately call the `onLoad` method. It calls this method when the plugin is first loaded onto the server, which can be at any time. I believe there may be some unique behavior in relation to the ClassLoader as well, but I am not 100% sure.

**Comment by caoccao** [comment]
Javet deploys a `.so` file to `/tmp/javet` at the beginning. It seems your application doesn't have enough permission over that path. Could you try the following before launching your application?

``` shell
rm -rf /tmp/javet
mkdir /tmp/javet
chmod 777 /tmp/javet
```
